/**
 * SEED / DEMO DATA DEFINITION - entirely fictional.
 *
 * Every person, company, handle and coordinate below is invented for testing the
 * 100 m proximity matcher. No real people, no real accounts, no real locations
 * beyond the public stadium used as an arbitrary map anchor.
 *
 * `distanceM` / `bearingDeg` are *designed* values: the generator converts them
 * into coordinates with `destinationPoint`, so the fixture set exercises exact
 * distances (99 m in, 101 m out) rather than hand-typed lat/lng guesses.
 */
import type { Attribute } from '@/lib/types';

export const SEED_NOTICE =
  'SEED/DEMO DATA - entirely fictional people generated for local testing. Do not treat as real personal data.';

/** Arbitrary public landmark used as the demo origin. */
export const ANCHOR = {
  lat: 51.5386,
  lng: -0.0166,
  label: 'London Stadium forecourt (demo anchor)',
};

export const RADIUS_M = 100;

/** The demo viewer: all distances in this file are relative to this person. */
export const VIEWER_HANDLE = 'demo_viewer';

export interface PersonSpec {
  handle: string;
  displayName: string;
  avatarEmoji: string;
  headline: string;
  attributes: Attribute[];
  /** Designed straight-line distance from the anchor, in metres. */
  distanceM: number;
  /** Designed bearing from the anchor, degrees clockwise from north. */
  bearingDeg: number;
  accuracyM: number;
  discoverable: boolean;
  ghosted: boolean;
  fixAgeSeconds: number;
  caseLabel: string;
}

const a = (
  kind: Attribute['kind'],
  slug: string,
  label: string,
  visibility: Attribute['visibility'] = 'public',
  weight = 1,
): Attribute => ({ kind, slug, label, visibility, weight });

/**
 * 50 fictional people. Person 1 is the viewer; the remaining 49 are spread
 * across the 100 m threshold and the filter edge cases the matcher must honour.
 */
export const PEOPLE: PersonSpec[] = [
  {
    handle: VIEWER_HANDLE,
    displayName: 'Demo Viewer',
    avatarEmoji: '🧭',
    headline: 'Seed account used as the map centre',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('sport', 'bouldering', 'Bouldering'),
      a('interest', 'board-games', 'Board games'),
      a('interest', 'street-food', 'Street food'),
      a('interest', 'vinyl-records', 'Vinyl records'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
      a('language', 'portuguese', 'Portuguese'),
      a('goal', 'find-running-buddy', 'Find a running buddy'),
    ],
    distanceM: 0,
    bearingDeg: 0,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 3,
    caseLabel: 'viewer (map centre)',
  },

  // --- Inner band: < 25 m, strong overlap -------------------------------
  {
    handle: 'ada_kestrel',
    displayName: 'Ada Kestrel',
    avatarEmoji: '🦅',
    headline: 'Logistics analyst, permanently hungry',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('interest', 'street-food', 'Street food'),
      a('goal', 'find-running-buddy', 'Find a running buddy'),
    ],
    distanceM: 6,
    bearingDeg: 12,
    accuracyM: 6,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 4,
    caseLabel: 'inner band, same company + sport + goal',
  },
  {
    handle: 'bruno_maple',
    displayName: 'Bruno Maple',
    avatarEmoji: '🍁',
    headline: 'Ops rota wrangler',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'bouldering', 'Bouldering'),
      a('interest', 'vinyl-records', 'Vinyl records'),
      a('language', 'portuguese', 'Portuguese'),
    ],
    distanceM: 14,
    bearingDeg: 78,
    accuracyM: 9,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 11,
    caseLabel: 'inner band, four shared attributes',
  },
  {
    handle: 'cleo_ravensworth',
    displayName: 'Cleo Ravensworth',
    avatarEmoji: '🎧',
    headline: 'Sound engineer, crate digger',
    attributes: [
      a('company', 'harbourline-audio', 'Harbourline Audio'),
      a('interest', 'vinyl-records', 'Vinyl records'),
      a('interest', 'board-games', 'Board games'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 21,
    bearingDeg: 145,
    accuracyM: 7,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 6,
    caseLabel: 'inner band, shared school + interests, different company',
  },
  {
    handle: 'dev_pillar',
    displayName: 'Dev Pillar',
    avatarEmoji: '🧱',
    headline: 'Bricklayer turned site planner',
    attributes: [
      a('company', 'quayside-build', 'Quayside Build'),
      a('sport', 'bouldering', 'Bouldering'),
      a('goal', 'find-running-buddy', 'Find a running buddy'),
    ],
    distanceM: 24.4,
    bearingDeg: 201,
    accuracyM: 5,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 8,
    caseLabel: 'just inside the 25 m bucket edge',
  },

  // --- Bucket boundary probes ------------------------------------------
  {
    handle: 'elin_frost',
    displayName: 'Elin Frost',
    avatarEmoji: '❄️',
    headline: 'Cold-chain scheduler',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'sea-swimming', 'Sea swimming'),
    ],
    distanceM: 25,
    bearingDeg: 260,
    accuracyM: 6,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 9,
    caseLabel: 'exactly 25 m -> belongs in the 25-50 m bucket',
  },
  {
    handle: 'ferris_gale',
    displayName: 'Ferris Gale',
    avatarEmoji: '🌬️',
    headline: 'Wind turbine technician',
    attributes: [
      a('company', 'orbit-energy', 'Orbit Energy'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 49.6,
    bearingDeg: 33,
    accuracyM: 11,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 15,
    caseLabel: 'just inside the 50 m bucket edge',
  },
  {
    handle: 'greta_lomond',
    displayName: 'Greta Lomond',
    avatarEmoji: '🏔️',
    headline: 'Climbing coach',
    attributes: [
      a('company', 'summit-collective', 'Summit Collective'),
      a('sport', 'bouldering', 'Bouldering'),
      a('goal', 'find-training-partner', 'Find a training partner'),
    ],
    distanceM: 50,
    bearingDeg: 96,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 12,
    caseLabel: 'exactly 50 m -> still the 25-50 m bucket',
  },
  {
    handle: 'hari_dune',
    displayName: 'Hari Dune',
    avatarEmoji: '🏜️',
    headline: 'Desert ultra hobbyist',
    attributes: [
      a('sport', 'trail-running', 'Trail running'),
      a('goal', 'find-running-buddy', 'Find a running buddy'),
      a('interest', 'street-food', 'Street food'),
    ],
    distanceM: 50.4,
    bearingDeg: 171,
    accuracyM: 10,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 20,
    caseLabel: 'just past 50 m -> 50-100 m bucket',
  },

  // --- The 100 m threshold, probed from both sides ----------------------
  {
    handle: 'ines_carrow',
    displayName: 'Ines Carrow',
    avatarEmoji: '📐',
    headline: 'Structural engineer',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 98,
    bearingDeg: 8,
    accuracyM: 6,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 7,
    caseLabel: '98 m - inside, high overlap (should rank despite distance)',
  },
  {
    handle: 'jonas_wren',
    displayName: 'Jonas Wren',
    avatarEmoji: '🐦',
    headline: 'Birdwatcher and barista',
    attributes: [
      a('interest', 'birdwatching', 'Birdwatching'),
      a('interest', 'street-food', 'Street food'),
      a('language', 'portuguese', 'Portuguese'),
    ],
    distanceM: 99,
    bearingDeg: 64,
    accuracyM: 9,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 18,
    caseLabel: '99 m - inside by 1 m (threshold probe)',
  },
  {
    handle: 'kaia_solent',
    displayName: 'Kaia Solent',
    avatarEmoji: '⛵',
    headline: 'Dinghy instructor',
    attributes: [
      a('sport', 'sailing', 'Sailing'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('interest', 'vinyl-records', 'Vinyl records'),
    ],
    distanceM: 99.9,
    bearingDeg: 119,
    accuracyM: 7,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 22,
    caseLabel: '99.9 m - inside by centimetres',
  },
  {
    handle: 'liam_ostrich',
    displayName: 'Liam Ostrich',
    avatarEmoji: '🥚',
    headline: 'Brunch obsessive',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'street-food', 'Street food'),
      a('sport', 'five-a-side', 'Five-a-side football'),
    ],
    distanceM: 100,
    bearingDeg: 187,
    accuracyM: 5,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 10,
    caseLabel: 'exactly 100 m - inclusive boundary, must be IN range',
  },
  {
    handle: 'mira_halcyon',
    displayName: 'Mira Halcyon',
    avatarEmoji: '🕊️',
    headline: 'Yoga teacher',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'bouldering', 'Bouldering'),
      a('interest', 'board-games', 'Board games'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 100.6,
    bearingDeg: 232,
    accuracyM: 5,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 9,
    caseLabel: 'just outside by 0.6 m - excluded despite the best overlap',
  },
  {
    handle: 'nils_barrow',
    displayName: 'Nils Barrow',
    avatarEmoji: '🛞',
    headline: 'Cargo bike courier',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'cycling', 'Cycling'),
      a('goal', 'find-running-buddy', 'Find a running buddy'),
    ],
    distanceM: 101,
    bearingDeg: 289,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 14,
    caseLabel: '101 m - out of range by 1 m (threshold probe)',
  },
  {
    handle: 'orla_pennyfar',
    displayName: 'Orla Pennyfar',
    avatarEmoji: '🎪',
    headline: 'Festival logistics',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 112,
    bearingDeg: 340,
    accuracyM: 12,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 25,
    caseLabel: 'out of range, same company (must not leak)',
  },

  // --- Accuracy / confidence edge cases --------------------------------
  {
    handle: 'pav_esker',
    displayName: 'Pav Esker',
    avatarEmoji: '📡',
    headline: 'Indoors with a terrible fix',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
    ],
    distanceM: 40,
    bearingDeg: 55,
    accuracyM: 148,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 30,
    caseLabel: 'accuracy 148 m - usable but only "nearby" confidence',
  },
  {
    handle: 'quinn_stellar',
    displayName: 'Quinn Stellar',
    avatarEmoji: '🛰️',
    headline: 'Basement office, no sky view',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'board-games', 'Board games'),
      a('sport', 'bouldering', 'Bouldering'),
    ],
    distanceM: 30,
    bearingDeg: 300,
    accuracyM: 220,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 35,
    caseLabel: 'accuracy 220 m - rejected as unusable (> 150 m cap)',
  },
  {
    handle: 'rune_tallow',
    displayName: 'Rune Tallow',
    avatarEmoji: '🕯️',
    headline: 'Candlemaker',
    attributes: [
      a('interest', 'crafts', 'Crafts'),
      a('interest', 'street-food', 'Street food'),
    ],
    distanceM: 88,
    bearingDeg: 15,
    accuracyM: 40,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 45,
    caseLabel: 'inside but wide error bars -> "nearby", not "certain"',
  },

  // --- Freshness edge cases --------------------------------------------
  {
    handle: 'sena_orrery',
    displayName: 'Sena Orrery',
    avatarEmoji: '🔭',
    headline: 'Planetarium guide',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'astronomy', 'Astronomy'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 45,
    bearingDeg: 210,
    accuracyM: 10,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 61,
    caseLabel: 'fix 61 s old - freshness decay starts',
  },
  {
    handle: 'tomas_vane',
    displayName: 'Tomas Vane',
    avatarEmoji: '🌀',
    headline: 'Weather nerd',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 60,
    bearingDeg: 240,
    accuracyM: 9,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 299,
    caseLabel: 'fix 299 s old - just inside the 5 min staleness cutoff',
  },
  {
    handle: 'ula_brightwater',
    displayName: 'Ula Brightwater',
    avatarEmoji: '💧',
    headline: 'Left her phone on a bench',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'bouldering', 'Bouldering'),
      a('interest', 'street-food', 'Street food'),
    ],
    distanceM: 35,
    bearingDeg: 130,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 420,
    caseLabel: 'fix 7 min old - dropped as stale',
  },

  // --- Consent / visibility edge cases ---------------------------------
  {
    handle: 'vic_hollows',
    displayName: 'Vic Hollows',
    avatarEmoji: '🚪',
    headline: 'Discoverability switched off',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 12,
    bearingDeg: 80,
    accuracyM: 6,
    discoverable: false,
    ghosted: false,
    fixAgeSeconds: 5,
    caseLabel: 'opted out - never appears, however close',
  },
  {
    handle: 'wren_castellan',
    displayName: 'Wren Castellan',
    avatarEmoji: '👻',
    headline: 'In ghost mode for an hour',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'vinyl-records', 'Vinyl records'),
    ],
    distanceM: 18,
    bearingDeg: 350,
    accuracyM: 7,
    discoverable: true,
    ghosted: true,
    fixAgeSeconds: 6,
    caseLabel: 'ghost mode - temporarily invisible',
  },
  {
    handle: 'xan_petrel',
    displayName: 'Xan Petrel',
    avatarEmoji: '🚫',
    headline: 'Blocked the viewer',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
    ],
    distanceM: 9,
    bearingDeg: 44,
    accuracyM: 5,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 4,
    caseLabel: 'block in place - filtered in both directions',
  },
  {
    handle: 'yara_quill',
    displayName: 'Yara Quill',
    avatarEmoji: '🖋️',
    headline: 'Private about her employer',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight', 'private'),
      a('interest', 'board-games', 'Board games'),
      a('school', 'thameside-poly', 'Thameside Polytechnic', 'matches'),
    ],
    distanceM: 32,
    bearingDeg: 22,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 12,
    caseLabel: 'private/matches visibility - scores but is not named',
  },
  {
    handle: 'zeb_marlow',
    displayName: 'Zeb Marlow',
    avatarEmoji: '🎲',
    headline: 'Runs a dice cafe',
    attributes: [
      a('interest', 'board-games', 'Board games'),
      a('interest', 'street-food', 'Street food'),
      a('language', 'portuguese', 'Portuguese', 'matches'),
    ],
    distanceM: 41,
    bearingDeg: 305,
    accuracyM: 9,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 16,
    caseLabel: 'mixed visibility, no company overlap',
  },

  // --- Zero / weak overlap (score floor) -------------------------------
  {
    handle: 'aster_moraine',
    displayName: 'Aster Moraine',
    avatarEmoji: '🧊',
    headline: 'Glaciologist, shares nothing',
    attributes: [
      a('company', 'polar-survey', 'Polar Survey'),
      a('sport', 'curling', 'Curling'),
      a('interest', 'ice-cores', 'Ice cores'),
    ],
    distanceM: 15,
    bearingDeg: 100,
    accuracyM: 6,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 8,
    caseLabel: 'very close, zero overlap - suppressed by the score floor',
  },
  {
    handle: 'basil_quorn',
    displayName: 'Basil Quorn',
    avatarEmoji: '🥬',
    headline: 'Allotment evangelist',
    attributes: [
      a('company', 'green-verge', 'Green Verge'),
      a('interest', 'gardening', 'Gardening'),
      a('language', 'welsh', 'Welsh'),
    ],
    distanceM: 27,
    bearingDeg: 190,
    accuracyM: 7,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 13,
    caseLabel: 'no overlap at all',
  },
  {
    handle: 'clover_ashdown',
    displayName: 'Clover Ashdown',
    avatarEmoji: '🍀',
    headline: 'Only shares one common interest',
    attributes: [
      a('company', 'lantern-legal', 'Lantern Legal'),
      a('interest', 'street-food', 'Street food'),
    ],
    distanceM: 72,
    bearingDeg: 20,
    accuracyM: 10,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 24,
    caseLabel: 'single common interest at distance - borderline score',
  },

  // --- Ordinary in-range population -----------------------------------
  {
    handle: 'fen_arbour',
    displayName: 'Fen Arbour',
    avatarEmoji: '🌳',
    headline: 'Urban forester',
    attributes: [
      a('company', 'green-verge', 'Green Verge'),
      a('sport', 'trail-running', 'Trail running'),
      a('goal', 'find-running-buddy', 'Find a running buddy'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 63,
    bearingDeg: 275,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 19,
    caseLabel: 'in range, shared school + goal',
  },
  {
    handle: 'gio_saffron',
    displayName: 'Gio Saffron',
    avatarEmoji: '🍲',
    headline: 'Street food stall owner',
    attributes: [
      a('company', 'saffron-street', 'Saffron Street'),
      a('interest', 'street-food', 'Street food'),
      a('language', 'portuguese', 'Portuguese'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 76,
    bearingDeg: 108,
    accuracyM: 12,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 27,
    caseLabel: 'in range, three shared attributes at distance',
  },
  {
    handle: 'hollis_penrose',
    displayName: 'Hollis Penrose',
    avatarEmoji: '🧩',
    headline: 'Puzzle designer',
    attributes: [
      a('company', 'penrose-puzzles', 'Penrose Puzzles'),
      a('interest', 'board-games', 'Board games'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 84,
    bearingDeg: 199,
    accuracyM: 10,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 23,
    caseLabel: 'in range, board games + school',
  },
  {
    handle: 'ivo_marchetti',
    displayName: 'Ivo Marchetti',
    avatarEmoji: '☕',
    headline: 'Roastery apprentice',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'coffee', 'Speciality coffee'),
      a('sport', 'five-a-side', 'Five-a-side football'),
    ],
    distanceM: 68,
    bearingDeg: 320,
    accuracyM: 9,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 26,
    caseLabel: 'in range, colleague and footballer',
  },
  {
    handle: 'juno_pike',
    displayName: 'Juno Pike',
    avatarEmoji: '🎣',
    headline: 'River guide',
    attributes: [
      a('company', 'riverbend-tours', 'Riverbend Tours'),
      a('sport', 'kayaking', 'Kayaking'),
      a('interest', 'birdwatching', 'Birdwatching'),
    ],
    distanceM: 91,
    bearingDeg: 250,
    accuracyM: 13,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 31,
    caseLabel: 'in range, no overlap - below the floor',
  },
  {
    handle: 'kit_ferrous',
    displayName: 'Kit Ferrous',
    avatarEmoji: '🔧',
    headline: 'Bike mechanic',
    attributes: [
      a('company', 'ferrous-cycles', 'Ferrous Cycles'),
      a('sport', 'cycling', 'Cycling'),
      a('sport', 'bouldering', 'Bouldering'),
      a('goal', 'find-training-partner', 'Find a training partner'),
    ],
    distanceM: 47,
    bearingDeg: 12,
    accuracyM: 7,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 14,
    caseLabel: 'in range, shared sport only',
  },
  {
    handle: 'lore_ashby',
    displayName: 'Lore Ashby',
    avatarEmoji: '📚',
    headline: 'Archivist',
    attributes: [
      a('company', 'thameside-archive', 'Thameside Archive'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
      a('interest', 'vinyl-records', 'Vinyl records'),
      a('language', 'portuguese', 'Portuguese'),
    ],
    distanceM: 53,
    bearingDeg: 88,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 18,
    caseLabel: 'in range, school + interest + language',
  },
  {
    handle: 'mose_kilburn',
    displayName: 'Mose Kilburn',
    avatarEmoji: '🥁',
    headline: 'Session drummer',
    attributes: [
      a('company', 'harbourline-audio', 'Harbourline Audio'),
      a('interest', 'vinyl-records', 'Vinyl records'),
      a('sport', 'five-a-side', 'Five-a-side football'),
    ],
    distanceM: 29,
    bearingDeg: 168,
    accuracyM: 6,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 10,
    caseLabel: 'in range, two shared attributes close by',
  },
  {
    handle: 'nadia_orpheus',
    displayName: 'Nadia Orpheus',
    avatarEmoji: '🎭',
    headline: 'Stage manager',
    attributes: [
      a('company', 'orpheus-stage', 'Orpheus Stage'),
      a('interest', 'theatre', 'Theatre'),
      a('interest', 'board-games', 'Board games'),
      a('language', 'portuguese', 'Portuguese'),
    ],
    distanceM: 79,
    bearingDeg: 40,
    accuracyM: 10,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 29,
    caseLabel: 'in range, interests + language',
  },
  {
    handle: 'ozzy_flint',
    displayName: 'Ozzy Flint',
    avatarEmoji: '🔥',
    headline: 'Blacksmith',
    attributes: [
      a('company', 'flint-forge', 'Flint Forge'),
      a('sport', 'bouldering', 'Bouldering'),
      a('interest', 'crafts', 'Crafts'),
    ],
    distanceM: 94,
    bearingDeg: 128,
    accuracyM: 12,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 33,
    caseLabel: 'in range at the far edge, one shared sport',
  },
  {
    handle: 'peri_solstice',
    displayName: 'Peri Solstice',
    avatarEmoji: '🌞',
    headline: 'Solar installer',
    attributes: [
      a('company', 'orbit-energy', 'Orbit Energy'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('goal', 'find-running-buddy', 'Find a running buddy'),
    ],
    distanceM: 66,
    bearingDeg: 220,
    accuracyM: 9,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 20,
    caseLabel: 'in range, sport + goal',
  },
  {
    handle: 'rafi_underwood',
    displayName: 'Rafi Underwood',
    avatarEmoji: '🌲',
    headline: 'Carpenter',
    attributes: [
      a('company', 'quayside-build', 'Quayside Build'),
      a('interest', 'crafts', 'Crafts'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 22,
    bearingDeg: 275,
    accuracyM: 7,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 11,
    caseLabel: 'in range, shared school nearby',
  },

  // --- Out of range population ----------------------------------------
  {
    handle: 'suri_calder',
    displayName: 'Suri Calder',
    avatarEmoji: '🚉',
    headline: 'On the platform, one street over',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 180,
    bearingDeg: 55,
    accuracyM: 9,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 15,
    caseLabel: 'out of range at 180 m',
  },
  {
    handle: 'thane_gable',
    displayName: 'Thane Gable',
    avatarEmoji: '🏗️',
    headline: 'Crane operator',
    attributes: [
      a('company', 'quayside-build', 'Quayside Build'),
      a('sport', 'bouldering', 'Bouldering'),
    ],
    distanceM: 260,
    bearingDeg: 140,
    accuracyM: 11,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 22,
    caseLabel: 'out of range at 260 m',
  },
  {
    handle: 'uma_veldt',
    displayName: 'Uma Veldt',
    avatarEmoji: '🦓',
    headline: 'Zoologist',
    attributes: [
      a('company', 'veldt-research', 'Veldt Research'),
      a('interest', 'wildlife', 'Wildlife'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 540,
    bearingDeg: 300,
    accuracyM: 14,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 40,
    caseLabel: 'out of range at 540 m',
  },
  {
    handle: 'vero_lindqvist',
    displayName: 'Vero Lindqvist',
    avatarEmoji: '🚋',
    headline: 'Tram driver',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('interest', 'vinyl-records', 'Vinyl records'),
      a('language', 'portuguese', 'Portuguese'),
    ],
    distanceM: 1200,
    bearingDeg: 20,
    accuracyM: 16,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 50,
    caseLabel: 'out of range at 1.2 km, strong overlap',
  },
  {
    handle: 'wilder_krane',
    displayName: 'Wilder Krane',
    avatarEmoji: '✈️',
    headline: 'Cabin crew, different city',
    attributes: [
      a('company', 'nimbus-freight', 'Nimbus Freight'),
      a('sport', 'five-a-side', 'Five-a-side football'),
      a('school', 'thameside-poly', 'Thameside Polytechnic'),
    ],
    distanceM: 15000,
    bearingDeg: 75,
    accuracyM: 20,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 60,
    caseLabel: 'out of range at 15 km',
  },

  // --- Coordinate-system edge cases ------------------------------------
  {
    handle: 'xiu_meridian',
    displayName: 'Xiu Meridian',
    avatarEmoji: '🗺️',
    headline: 'Antimeridian west side',
    attributes: [
      a('company', 'meridian-charts', 'Meridian Charts'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 0,
    bearingDeg: 0,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 12,
    caseLabel: 'antimeridian pair A (lng 179.9999) - fixed coordinates',
  },
  {
    handle: 'yusuf_dateline',
    displayName: 'Yusuf Dateline',
    avatarEmoji: '🧮',
    headline: 'Antimeridian east side',
    attributes: [
      a('company', 'meridian-charts', 'Meridian Charts'),
      a('interest', 'board-games', 'Board games'),
    ],
    distanceM: 0,
    bearingDeg: 0,
    accuracyM: 8,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 12,
    caseLabel: 'antimeridian pair B (lng -179.9999) - ~22 m from pair A',
  },
  {
    handle: 'zola_polaris',
    displayName: 'Zola Polaris',
    avatarEmoji: '🧊',
    headline: 'High-latitude research post',
    attributes: [
      a('company', 'polar-survey', 'Polar Survey'),
      a('sport', 'bouldering', 'Bouldering'),
    ],
    distanceM: 0,
    bearingDeg: 0,
    accuracyM: 25,
    discoverable: true,
    ghosted: false,
    fixAgeSeconds: 90,
    caseLabel: 'lat 89.9 - polar convergence edge case, fixed coordinates',
  },
];

/**
 * Coordinates that must not be derived from the anchor: antimeridian and polar
 * probes. Keyed by handle, applied by the generator after the bearing maths.
 */
export const FIXED_COORDINATES: Record<string, { lat: number; lng: number }> = {
  xiu_meridian: { lat: -16.5, lng: 179.9999 },
  yusuf_dateline: { lat: -16.5, lng: -179.9999 },
  zola_polaris: { lat: 89.9, lng: 42 },
};

/** Blocks are bidirectional in effect; the fixture records one direction. */
export const BLOCKS: Array<{ blocker: string; blocked: string; note: string }> = [
  {
    blocker: 'xan_petrel',
    blocked: VIEWER_HANDLE,
    note: 'target blocked the viewer - viewer must not see them',
  },
  {
    blocker: VIEWER_HANDLE,
    blocked: 'basil_quorn',
    note: 'viewer blocked the target - target must not appear',
  },
];
